### ISSUE TITLE
Add new Valorant API (Valorant party invite code)

### ISSUE THREAD

**Issue by kvrzh** [tanishqmanuja/valorant-api-client#10]
Hi, It is very convenient to use your library to work with Valorant.
It would be cool to have support for the new API (Valorant party invite code)

```
create/reset:
POST
https://glz-{region}-1.{shard}.a.pvp.net/parties/v1/parties/{party_uuid}/invitecode

only retrieve:
GET to same

join: (prolly, have not tested)
POST https://glz-{region}-1.{shard}.a.pvp.net/parties/v1/players/joinbycode/{inv_code} 
```

etc

**Comment by tanishqmanuja** [comment]
Thanks for the feedback 😸

This project uses endpoints directly from a downstream fork of https://github.com/techchrism/valorant-api-docs. For that reason, I dont want to maintain a separate list of endpoints.

For now we can do the following,
- Open a issue on upstream api types/docs repo, as soon as it is resolved .. endpoints will get auto generated 
- For time being I can expose a method for calling non-included endpoints.

**Comment by kvrzh** [comment]
1. I will create issue for them)
2. Will be nice to have method for calling non-included endpoints btw)

**Comment by tanishqmanuja** [comment]
Added in v1.4.0

**Comment by xaronnn** [comment]
How can i get current player current party uuid and party code?

**Comment by tanishqmanuja** [comment]
@xaronnn, My bad, I forgot to add callEndpoint in the rewrite. Now it has been added as "request". You can use `vapic.remote.request()`
